name: Deploy
on:
  push:
    branches:
      - main

jobs:
  run-migrations:
    name: Run Migrations
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npm run db:migrate